name: Build the markdown source files

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    container: dalibo/pandocker
    steps:
      - uses: actions/checkout@v3
      - run: pip install -r requirements.txt
      - run: make sample -B

